language: scala
scala:
  - 2.10.3
jdk:
  - oraclejdk8
after_success:
    "curl --ftp-create-dirs -T uploadfilename -u $FTP_USER:$FTP_PASSWORD ftp://apps.markdessain.com/files/"

secure: "0IMPTBtjdXyAnK2o1sp86EJNMk5waaqW1FmyVlVt8Cx1hd9m4ZiKtXbRlslxh8Kz7KoMZpZoi4K47vDkEI0WRjFvEHE2k3BG6uk7nCujVdR2nqsCnYIoeXQ/llNuEQZNhQvNCwv4Sn0sLIcm9E2MtpVRbFABjAmF8WvL2UWPGdw="
secure: "hP43m56E/hk85yG3ZqO2GdukruYEOdz+vGj7R0iZjTWrFWDEwBd16PgBel11kSamhL35LIi3y17hlfA0iKUllSf0yAK3NMewBQWGz5F5js1+IUJQdYsB4nxA9gfvBZ8C3lDKdxTP02vs5EJAni2RHpmRjdExN7wePmpRAb0kYJc="

